project_name: ring-api
builds:
  - id: ring-api
    main: ./cmd/ring-api/main.go
    binary: ring-api
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - format: zip
checksum:
  name_template: 'checksums.txt'
release:
  draft: false
